default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  reconnect: false
  username: bhuser
  password: '363099'
  host: localhost

development:
  <<: *default
  database: sneakers_dev

test:
  <<: *default
  database: sneakers_test

production:
  <<: *default
  database: sneakers_pd
